# Generated by Django 4.2.17 on 2024-12-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_user_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_pass',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
